FROM ubuntu:16.04
MAINTAINER leijiangping <leijiang21@126.com>
RUN apt-get update &&apt-get install wget -y  && apt-get install git -y
RUN apt-get install inetutils-ping  -y 
RUN apt-get install net-tools  
RUN apt-get install vim  -y 






